#Goal - i have Lint, Build, Test the code for Frontend & Backend
#Then Push the images to Docker hub 

name: CI

on:
    push:
        branches: [advanced]
      
jobs:
  code-lint:
  frontend:
  backend:

    